const defaultPatterns = [
  { pattern: 'clique aqui para ganhar',       type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 4231 },
  { pattern: 'bit.ly/',                        type: 'url',     language: 'both', severity: 'high',   status: 'active', matchCount: 3108 },
  { pattern: 'confirme seus dados',            type: 'keyword', language: 'pt',   severity: 'medium', status: 'active', matchCount: 2440 },
  { pattern: 'promoção exclusiva',             type: 'keyword', language: 'pt',   severity: 'low',    status: 'active', matchCount: 1890 },
  { pattern: 'senha expirada',                 type: 'keyword', language: 'pt',   severity: 'medium', status: 'active', matchCount: 1312 },
  { pattern: 'click here to win',              type: 'keyword', language: 'en',   severity: 'high',   status: 'active', matchCount:  892 },
  { pattern: 'tinyurl.com',                    type: 'url',     language: 'both', severity: 'medium', status: 'active', matchCount:  567 },
  { pattern: 'verify your account',            type: 'keyword', language: 'en',   severity: 'high',   status: 'inactive', matchCount: 345 },
  { pattern: '(\\d{3}-\\d{4}-\\d{4})',         type: 'regex',   language: 'both', severity: 'low',    status: 'active', matchCount:  234 },
  { pattern: 'você foi selecionado',           type: 'keyword', language: 'pt',   severity: 'medium', status: 'active', matchCount:  189 },
  { pattern: 'conta bancária foi bloqueada',   type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 2190 },
  { pattern: 'transferência pendente',         type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 1650 },
  { pattern: 'acesso suspeito',                type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 1420 },
  { pattern: 'desbloqueie sua conta',          type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount:  980 },
  { pattern: 'rb.gy/',                         type: 'url',     language: 'both', severity: 'high',   status: 'active', matchCount: 1540 },
  { pattern: 'abre.ai/',                       type: 'url',     language: 'both', severity: 'high',   status: 'active', matchCount:  812 },
  { pattern: 'apostas grátis',                 type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 1874 },
  { pattern: 'gira grátis',                    type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount:  730 },
  { pattern: 'roleta',                         type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount:  605 },
  { pattern: 'bónus',                          type: 'keyword', language: 'pt',   severity: 'medium', status: 'active', matchCount:  490 },
  { pattern: 'chat.whatsapp.com/',             type: 'url',     language: 'both', severity: 'medium', status: 'active', matchCount:  980 },
  { pattern: 'fazer dinheiro na Internet',     type: 'keyword', language: 'pt',   severity: 'medium', status: 'active', matchCount:  420 },
  { pattern: 'comunidade.*fazer dinheiro',     type: 'regex',   language: 'pt',   severity: 'medium', status: 'active', matchCount:  310 },
  { pattern: 'você ganhou',                    type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 1760 },
  { pattern: 'clique aqui para resgatar',      type: 'keyword', language: 'pt',   severity: 'high',   status: 'active', matchCount: 1230 },
]

module.exports = { defaultPatterns }
